replicaCount: 2

image:
  repository: aakash0908/gitops-go-app
  tag: c64c804
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: gitops-go-app.duckdns.org

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
